### ISSUE TITLE
SIGTERM SignalException: Init error when loading handler

### ISSUE THREAD

**Issue by metaskills** [rails-lambda/lamby#155]
Been seeing these a lot more lately on the latest cookiecutter with Ubuntu image. Normally I would only see these on shutdown but I am starting to see them more on first invoke/init. Here is a screenshot of the stack trace. May fork or PR here. https://github.com/aws/aws-lambda-ruby-runtime-interface-client

![Screenshot 2023-07-04 at 9 12 47 AM](https://github.com/rails-lambda/lamby/assets/2381/41a7c43d-4c35-417c-ab22-92c56bb3eb26)

**Comment by plukevdh** [comment]
Questions because I'm seeing this elsewhere as well, have seen very few reports of this from others, and I'm trying to narrow down causes:
1. Does this only happen during startups of newly deployed code, i.e., did you deploy new code and then first invocations caused this error?
2. Do you have any additional extensions loaded?

I wonder whether or not lambda gets caught terminating new inits along side old instances of the runtime by broadcasting SIGTERMs differently than before...

**Comment by metaskills** [comment]
I'm gonna turn on these two env vars and monitor things.

```
LAMBDA_PUNCH_LOG_LEVEL: debug
CRYPTEIA_DEBUG: true
```

**Comment by plukevdh** [comment]
"along side" meaning that a sigterm gets broadcast to terminate old lambdas running while the new lambdas are attempting to init and both old and new versions of the lambda get terminated and then the new version starts again. Just a theory. I'd need some kind of sha or other code version identifier to confirm that. For us, we resolved by manually trapping the sigterm per [the details suggested here](https://github.com/aws-samples/graceful-shutdown-with-aws-lambda).

**Comment by metaskills** [comment]
Thanks! Just learned about this today too:

- https://twitter.com/wm_matuszewski/status/1680071801156653056?s=43&t=az8mU_0mUrWwmcIF6DD2OA
- https://github.com/aws-samples/graceful-shutdown-with-aws-lambda/tree/main/nodejs-demo
